
[build.environment]
  NODE_VERSION = "20"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "pnpm run build"


[[redirects]]
  from = "/2023/githubeinsteiger/pdf"
  to = "https://github.com/nyxb/talks/blob/main/2023-12-02/2023-12-02-github-einsteiger-de.pdf?raw=true"
  status = 302

[[redirects]]
  from = "/2023-12-02/pdf"
  to = "https://github.com/nyxb/talks/blob/main/2023-12-02/2023-12-02-github-einsteiger-de.pdf?raw=true"
  status = 302

[[redirects]]
  from = "/2023/githubeinsteiger/src"
  to = "https://github.com/nyxb/talks/tree/main/2023-12-02"
  status = 302

[[redirects]]
  from = "2023-12-02"
  to = "https://talks.nyxb.nexus{base}"
  status = 301

[[redirects]]
  from = "/2023/githubeinsteiger/*"
  to = "/2023/githubeinsteiger/index.html"
  status = 200

[[redirects]]
  from = "/2024/joypixonboarding/src"
  to = "https://github.com/nyxb/talks/tree/main/2024-01-07"
  status = 302

[[redirects]]
  from = "2024-01-07"
  to = "https://talks.nyxb.nexus{base}"
  status = 301

[[redirects]]
  from = "/2024/joypixonboarding/*"
  to = "/2024/joypixonboarding/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://nyxb.nexus/talks"
  status = 302
